##
 # @file mk/make.py
 # @date 2026/08/07
 # 
 # @brief Makefile-style build entry for Dandelion (Nuitka standalone).
 #
 # @usage
 #   python mk/make.py            : full build (same as 'all')
 #   python mk/make.py clean      : remove runtime caches and build artifacts
 #   python mk/make.py all        : build standalone executable into build/
 #   python mk/make.py version    : print project name and version
 #   python mk/make.py sign       : sign Windows executable (placeholder)
 #

import configparser
import datetime
import importlib.util
import os
import platform
import shlex
import shutil
import subprocess
import sys
import tomllib

##
 # @brief Directory of this script (mk/).
 #
MK_DIR = os.path.dirname(os.path.abspath(__file__))

##
 # @brief Project root directory (parent of mk/).
 #
ROOT_DIR = os.path.dirname(MK_DIR)

##
 # @brief Usage help text.
 #
USAGE = """Usage: python mk/make.py [target]

Targets:
  (none)   : full build (same as 'all')
  all      : build standalone executable into build/
  clean    : remove runtime caches and build artifacts
  version  : print project name and version
  sign     : sign Windows executable (placeholder, P3)
  help     : show this help
"""

##
 # @brief Load mk/config/build.config (INI).
 #
 # @return configparser.ConfigParser instance.
 #
def _load_config():
    cfg = configparser.ConfigParser()
    cfg.read(os.path.join(MK_DIR, "config", "build.config"))
    return cfg
# End-def

##
 # @brief Load root pyproject.toml (TOML).
 #
 # @return dict parsed from pyproject.toml.
 #
def _load_pyproject():
    with open(os.path.join(ROOT_DIR, "pyproject.toml"), "rb") as f:
        return tomllib.load(f)
# End-with

##
 # @brief Get project name and version (single source of truth).
 #
 # @return (name, version) tuple.
 #
def _project_meta():
    meta = _load_pyproject()["project"]
    return meta["name"], meta["version"]
# End-def

##
 # @brief Check Nuitka availability in the current interpreter.
 #
def _check_nuitka():
    if importlib.util.find_spec("nuitka") is None:
        print("[-] Nuitka is not installed.")
        print("    Install with: pip install -e \".[dev]\"")
        sys.exit(1)
    # End-if
# End-def

##
 # @brief Generate mk/lib/build_info.py with build metadata.
 #
 # @param version Project version string.
 #
def _gen_build_info(version):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "##",
        " # @file mk/lib/build_info.py",
        " # @date " + now[:10],
        " # ",
        " # @brief Build metadata generated by mk/make.py. DO NOT EDIT.",
        " #",
        "",
        "VERSION = \"" + version + "\"",
        "BUILD_MODE = \"standalone\"",
        "BUILD_DATE = \"" + now + "\"",
        "PLATFORM = \"" + platform.system().lower() + "\"",
        "",
    ]
    path = os.path.join(MK_DIR, "lib", "build_info.py")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    # End-with
    print("[+] Generated " + os.path.relpath(path, ROOT_DIR))
# End-def

##
 # @brief Assemble and run the Nuitka standalone build.
 #
 # @param cfg     Build config (ConfigParser).
 # @param name    Project name (binary name).
 # @param version Project version string.
 #
def _run_nuitka(cfg, name, version):
    entry = os.path.join(ROOT_DIR, cfg.get("build", "entry", fallback="main.py"))
    output_dir = os.path.join(ROOT_DIR, cfg.get("build", "output_dir", fallback="build"))
    cache_dir = os.path.join(ROOT_DIR, cfg.get("build", "cache_dir", fallback=".nuitka-cache"))
    jobs = cfg.get("nuitka", "jobs", fallback="4")
    if sys.platform == "win32":
        # MSVC consumes large heap per compile unit; reduce parallelism to
        # avoid "C1002: compiler is out of heap space in pass 2".
        jobs = cfg.get("nuitka", "windows_jobs", fallback="2")
    # End-if
    extra_args = shlex.split(cfg.get("nuitka", "extra_args", fallback=""))

    cmd = [
        sys.executable, "-m", "nuitka",
        "--mode=standalone",
        "--output-dir=" + output_dir,
        "--output-filename=" + name,
        "--include-package=src",
        "--include-module=mk.lib.paths",
        "--include-module=mk.lib.build_info",
        "--assume-yes-for-downloads",
        "--jobs=" + jobs,
        "--static-libpython=no",
    ]

    # ----- @par Anti-Bloat Plugins & Deployment Flags -----
    cmd.append("--enable-plugin=anti-bloat")
    cmd.append("--noinclude-pytest-mode=nofollow")
    cmd.append("--noinclude-setuptools-mode=nofollow")
    cmd.append("--noinclude-unittest-mode=nofollow")
    cmd.append("--no-deployment-flag=excluded-module-usage")
    cmd.append("--no-deployment-flag=error-on-failed-import")

    # ----- @par Selective Compilation (Bypass C-Compilation) -----
    nofollow_str = cfg.get("nuitka", "nofollow_imports", fallback="")
    if nofollow_str:
        for pkg in [p.strip() for p in nofollow_str.split(",") if p.strip()]:
            cmd.append("--nofollow-import-to=" + pkg)
        # End-for
    # End-if

    # ----- @par Force Include Standard Modules -----
    std_mods_str = cfg.get("nuitka", "include_std_modules", fallback="")
    if std_mods_str:
        for mod in [m.strip() for m in std_mods_str.split(",") if m.strip()]:
            cmd.append("--include-module=" + mod)
        # End-for
    # End-if

    # ----- @par Windows-only options (PE version resource + icon) -----
    if sys.platform == "win32":
        company = cfg.get("build", "company", fallback="").strip()
        description = cfg.get("build", "description", fallback="").strip()

        if company:
            cmd.append("--company-name=" + company)
        # End-if
        if description:
            cmd.append("--file-description=" + description)
        # End-if

        cmd += [
            "--product-name=" + name,
            "--product-version=" + version,
            "--file-version=" + version,
        ]

        icon = os.path.join(ROOT_DIR, cfg.get("build", "icon", fallback="mk/config/dandelion.ico"))
        if os.path.exists(icon):
            cmd.append("--windows-icon-from-ico=" + icon)
        # End-if
    # End-if

    # ----- @par Extra user args -----
    cmd += extra_args

    # ----- @par Entry script -----
    cmd.append(entry)

    env = os.environ.copy()
    env["NUITKA_CACHE_DIR"] = cache_dir

    print("[*] Executing: " + " ".join(cmd))
    print("[*] Nuitka Cache Dir: " + cache_dir)
    result = subprocess.run(cmd, cwd=ROOT_DIR, env=env)
    if result.returncode != 0:
        print("[-] Build failed with exit code " + str(result.returncode))
        sys.exit(result.returncode)
    # End-if
# End-def

##
 # @brief Post-process Nuitka output into build/<name>/ layout.
 #
 # @param cfg     Build config (ConfigParser).
 # @param name    Project name (binary name).
 # @param version Project version string.
 #
def _postprocess(cfg, name, version):
    output_dir = os.path.join(ROOT_DIR, cfg.get("build", "output_dir", fallback="build"))
    entry = os.path.join(ROOT_DIR, cfg.get("build", "entry", fallback="main.py"))
    entry_base = os.path.splitext(os.path.basename(entry))[0]

    # Nuitka names the dist folder after the entry script (e.g. main.dist),
    # while --output-filename only controls the executable name inside it.
    dist_dir = os.path.join(output_dir, entry_base + ".dist")
    if not os.path.isdir(dist_dir):
        # Fallback: scan for a single *.dist folder in the output dir.
        if os.path.isdir(output_dir):
            candidates = [
                d for d in os.listdir(output_dir)
                if d.endswith(".dist") and os.path.isdir(os.path.join(output_dir, d))
            ]
            if len(candidates) == 1:
                dist_dir = os.path.join(output_dir, candidates[0])
            elif len(candidates) > 1:
                print("[-] Ambiguous Nuitka outputs: " + ", ".join(candidates))
                sys.exit(1)
            # End-if
        # End-if
    # End-if

    if not os.path.isdir(dist_dir):
        print("[-] Expected Nuitka output not found: " + dist_dir)
        sys.exit(1)
    # End-if

    # Rename <entry>.dist -> <name>/bin (C-style output layout).
    target_dir = os.path.join(output_dir, name)
    if os.path.isdir(target_dir):
        shutil.rmtree(target_dir)
    # End-if
    os.makedirs(target_dir)
    
    # Move the entire dist directory into the bin/ subfolder
    bin_dir = os.path.join(target_dir, "bin")
    os.rename(dist_dir, bin_dir)

    # ----- @par 1. Copy bypassed heavy packages from venv to bin/ -----
    copy_pkgs_str = cfg.get("nuitka", "copy_packages", fallback="")
    if copy_pkgs_str:
        print("[*] Copying bypassed python packages directly to bin/...")
        for pkg_name in [p.strip() for p in copy_pkgs_str.split(",") if p.strip()]:
            spec = importlib.util.find_spec(pkg_name)
            if spec and spec.submodule_search_locations:
                src_dir = spec.submodule_search_locations[0]
                dst_dir = os.path.join(bin_dir, pkg_name)
                # Ignore raw pyc caches to keep size small, Python will re-generate them at runtime if needed
                shutil.copytree(src_dir, dst_dir, ignore=shutil.ignore_patterns("__pycache__"))
                print("  [+] Copied package: " + pkg_name)
            elif spec and spec.origin:
                src_file = spec.origin
                dst_file = os.path.join(bin_dir, os.path.basename(src_file))
                shutil.copy2(src_file, dst_file)
                print("  [+] Copied module: " + pkg_name)
            else:
                print("  [-] Warning: Could not find package '" + pkg_name + "' in current python environment.")
            # End-if
        # End-for
    # End-if

    # ----- @par 2. Create required workspace directories -----
    print("[*] Creating workspace layout...")
    workspace_dirs = [".env", "llm/memory", "llm/skill", ".log"]
    for d in workspace_dirs:
        d_path = os.path.join(target_dir, d.replace("/", os.sep))
        os.makedirs(d_path, exist_ok=True)
        # Create a tiny .keep file so Git or ZIP archives preserve the empty folders
        with open(os.path.join(d_path, ".keep"), "w") as f:
            f.write("")
        # End-with
    # End-for
    print("  [+] Created directories: .env, llm, .log")

    # Write version file.
    with open(os.path.join(target_dir, "version.txt"), "w", encoding="utf-8") as f:
        f.write(version + "\n")
    # End-with

    exe_name = name + ".exe" if sys.platform == "win32" else name
    print("[+] Build success: " + os.path.join(bin_dir, exe_name))
    print("[+] Version file: " + os.path.join(target_dir, "version.txt"))
    print("[+] Nuitka intermediate kept at: " + os.path.join(output_dir, entry_base + ".build"))
# End-def

##
 # @brief Target: build standalone executable (default).
 #
def target_all():
    name, version = _project_meta()
    cfg = _load_config()

    mode = cfg.get("build", "mode", fallback="standalone").strip().lower()
    if mode != "standalone":
        print("[-] Unsupported build mode: " + mode + " (only 'standalone' is supported).")
        sys.exit(1)
    # End-if

    _check_nuitka()
    _gen_build_info(version)
    _run_nuitka(cfg, name, version)
    _postprocess(cfg, name, version)
# End-def

##
 # @brief Target: remove bytecode caches and build artifacts.
 #
def target_clean():
    print("[*] Cleaning bytecode caches...")
    removed = 0
    for dirpath, dirnames, filenames in os.walk(ROOT_DIR):
        if ".git" in dirnames:
            dirnames.remove(".git")
        # End-if
        if ".log" in dirnames:
            dirnames.remove(".log")
        # End-if
        if "__pycache__" in dirnames:
            shutil.rmtree(os.path.join(dirpath, "__pycache__"), ignore_errors=True)
            removed += 1
        # End-if
        for fn in filenames:
            if fn.endswith((".pyc", ".pyo")):
                os.remove(os.path.join(dirpath, fn))
                removed += 1
            # End-if
        # End-for
    # End-for
    print("[+] Removed " + str(removed) + " bytecode items.")

    # Remove build artifacts.
    cfg = _load_config()
    for key in ("output_dir", "cache_dir"):
        path = os.path.join(ROOT_DIR, cfg.get("build", key, fallback=""))
        if os.path.exists(path):
            shutil.rmtree(path, ignore_errors=True)
            print("[+] Removed " + os.path.relpath(path, ROOT_DIR))
        # End-if
    # End-for

    # Legacy dist/ directory.
    legacy = os.path.join(ROOT_DIR, "dist")
    if os.path.exists(legacy):
        shutil.rmtree(legacy, ignore_errors=True)
        print("[+] Removed dist/ (legacy)")
    # End-if
# End-def

##
 # @brief Target: print project name and version.
 #
def target_version():
    name, version = _project_meta()
    print("[+] " + name + " " + version)
# End-def

##
 # @brief Target: sign Windows executable (placeholder for P3).
 #
def target_sign():
    cfg = _load_config()
    enabled = cfg.getboolean("sign", "enabled", fallback=False)
    if not enabled:
        print("[-] Signing is disabled (mk/config/build.config [sign] enabled=false).")
        print("    Nothing to do.")
        return
    # End-if
    print("[-] Signing is not implemented yet (planned for P3).")
    sys.exit(1)
# End-def

##
 # @brief Target: print usage help.
 #
def target_help():
    print(USAGE)
# End-def

##
 # @brief Entry point: dispatch make targets.
 #
def main():
    target = sys.argv[1] if len(sys.argv) > 1 else "all"

    handlers = {
        "all": target_all,
        "clean": target_clean,
        "version": target_version,
        "sign": target_sign,
        "help": target_help,
        "-h": target_help,
        "--help": target_help,
    }

    handler = handlers.get(target)
    if handler is None:
        print("[-] Unknown target: " + target)
        print(USAGE)
        sys.exit(1)
    # End-if

    handler()
# End-def

if __name__ == "__main__":
    main()
