##
 # @file mk/make.py
 # @date 2026/08/07
 # 
 # @brief Makefile-style build entry for Dandelion (Nuitka standalone).
 #
 # @usage
 #   python mk/make.py            : full build (same as 'all')
 #   python mk/make.py clean      : remove runtime caches and build artifacts
 #   python mk/make.py all        : build standalone executable into build/
 #   python mk/make.py version    : print project name and version
 #   python mk/make.py sign       : sign Windows executable (placeholder)
 #

import configparser
import datetime
import importlib.util
import os
import platform
import shlex
import shutil
import subprocess
import sys
import tomllib

##
 # @brief Directory of this script (mk/).
 #
MK_DIR = os.path.dirname(os.path.abspath(__file__))

##
 # @brief Project root directory (parent of mk/).
 #
ROOT_DIR = os.path.dirname(MK_DIR)

##
 # @brief Usage help text.
 #
USAGE = """Usage: python mk/make.py [target]

Targets:
  (none)   : full build (same as 'all')
  all      : build standalone executable into build/
  clean    : remove runtime caches and build artifacts
  version  : print project name and version
  sign     : sign Windows executable (placeholder, P3)
  help     : show this help
"""

##
 # @brief Load mk/config/build.config (INI).
 #
 # @return configparser.ConfigParser instance.
 #
def _load_config():
    cfg = configparser.ConfigParser()
    cfg.read(os.path.join(MK_DIR, "config", "build.config"))
    return cfg
# End-def

##
 # @brief Load root pyproject.toml (TOML).
 #
 # @return dict parsed from pyproject.toml.
 #
def _load_pyproject():
    with open(os.path.join(ROOT_DIR, "pyproject.toml"), "rb") as f:
        return tomllib.load(f)
# End-with

##
 # @brief Get project name and version (single source of truth).
 #
 # @return (name, version) tuple.
 #
def _project_meta():
    meta = _load_pyproject()["project"]
    return meta["name"], meta["version"]
# End-def

##
 # @brief Check Nuitka availability in the current interpreter.
 #
def _check_nuitka():
    if importlib.util.find_spec("nuitka") is None:
        print("[-] Nuitka is not installed.")
        print("    Install with: pip install -e \".[dev]\"")
        sys.exit(1)
    # End-if
# End-def

##
 # @brief Generate mk/aux/build_info.py with build metadata.
 #
 # @param version Project version string.
 #
def _gen_build_info(version):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "##",
        " # @file mk/aux/build_info.py",
        " # @date " + now[:10],
        " # ",
        " # @brief Build metadata generated by mk/make.py. DO NOT EDIT.",
        " #",
        "",
        "VERSION = \"" + version + "\"",
        "BUILD_MODE = \"standalone\"",
        "BUILD_DATE = \"" + now + "\"",
        "PLATFORM = \"" + platform.system().lower() + "\"",
        "",
    ]
    path = os.path.join(MK_DIR, "aux", "build_info.py")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    # End-with
    print("[+] Generated " + os.path.relpath(path, ROOT_DIR))
# End-def

##
 # @brief Assemble and run the Nuitka standalone build.
 #
 # @param cfg     Build config (ConfigParser).
 # @param name    Project name (binary name).
 # @param version Project version string.
 #
def _run_nuitka(cfg, name, version):
    entry = os.path.join(ROOT_DIR, cfg.get("build", "entry", fallback="main.py"))
    output_dir = os.path.join(ROOT_DIR, cfg.get("build", "output_dir", fallback="build"))
    cache_dir = os.path.join(ROOT_DIR, cfg.get("build", "cache_dir", fallback=".nuitka-cache"))
    jobs = cfg.get("nuitka", "jobs", fallback="4")
    extra_args = shlex.split(cfg.get("nuitka", "extra_args", fallback=""))

    cmd = [
        sys.executable, "-m", "nuitka",
        "--mode=standalone",
        "--output-dir=" + output_dir,
        "--output-filename=" + name,
        "--include-package=src",
        "--include-module=mk.aux.paths",
        "--include-module=mk.aux.build_info",
        "--assume-yes-for-downloads",
        "--jobs=" + jobs,
        "--static-libpython=no",
    ]

    # ----- @par Windows-only options (PE version resource + icon) -----
    if sys.platform == "win32":
        company = cfg.get("build", "company", fallback="").strip()
        description = cfg.get("build", "description", fallback="").strip()

        if company:
            cmd.append("--company-name=" + company)
        # End-if
        if description:
            cmd.append("--file-description=" + description)
        # End-if

        cmd += [
            "--product-name=" + name,
            "--product-version=" + version,
            "--file-version=" + version,
        ]

        icon = os.path.join(ROOT_DIR, cfg.get("build", "icon", fallback="mk/config/dandelion.ico"))
        if os.path.exists(icon):
            cmd.append("--windows-icon-from-ico=" + icon)
        # End-if
    # End-if

    # ----- @par Extra user args -----
    cmd += extra_args

    # ----- @par Entry script -----
    cmd.append(entry)

    env = os.environ.copy()
    env["NUITKA_CACHE_DIR"] = cache_dir

    print("[*] Executing: " + " ".join(cmd))
    print("[*] Nuitka Cache Dir: " + cache_dir)
    result = subprocess.run(cmd, cwd=ROOT_DIR, env=env)
    if result.returncode != 0:
        print("[-] Build failed with exit code " + str(result.returncode))
        sys.exit(result.returncode)
    # End-if
# End-def

##
 # @brief Post-process Nuitka output into build/<name>/ layout.
 #
 # @param cfg     Build config (ConfigParser).
 # @param name    Project name (binary name).
 # @param version Project version string.
 #
def _postprocess(cfg, name, version):
    output_dir = os.path.join(ROOT_DIR, cfg.get("build", "output_dir", fallback="build"))
    dist_dir = os.path.join(output_dir, name + ".dist")
    target_dir = os.path.join(output_dir, name)

    if not os.path.isdir(dist_dir):
        print("[-] Expected Nuitka output not found: " + dist_dir)
        sys.exit(1)
    # End-if

    # Rename <name>.dist -> <name> (C-style output layout).
    if os.path.isdir(target_dir):
        shutil.rmtree(target_dir)
    # End-if
    os.rename(dist_dir, target_dir)

    # Write version file.
    with open(os.path.join(target_dir, "version.txt"), "w", encoding="utf-8") as f:
        f.write(version + "\n")
    # End-with

    exe_name = name + ".exe" if sys.platform == "win32" else name
    print("[+] Build success: " + os.path.join(target_dir, exe_name))
    print("[+] Version file: " + os.path.join(target_dir, "version.txt"))
    print("[+] Nuitka intermediate kept at: " + os.path.join(output_dir, name + ".build"))
# End-def

##
 # @brief Target: build standalone executable (default).
 #
def target_all():
    name, version = _project_meta()
    cfg = _load_config()

    mode = cfg.get("build", "mode", fallback="standalone").strip().lower()
    if mode != "standalone":
        print("[-] Unsupported build mode: " + mode + " (only 'standalone' is supported).")
        sys.exit(1)
    # End-if

    _check_nuitka()
    _gen_build_info(version)
    _run_nuitka(cfg, name, version)
    _postprocess(cfg, name, version)
# End-def

##
 # @brief Target: remove bytecode caches and build artifacts.
 #
def target_clean():
    print("[*] Cleaning bytecode caches...")
    removed = 0
    for dirpath, dirnames, filenames in os.walk(ROOT_DIR):
        if ".git" in dirnames:
            dirnames.remove(".git")
        # End-if
        if ".log" in dirnames:
            dirnames.remove(".log")
        # End-if
        if "__pycache__" in dirnames:
            shutil.rmtree(os.path.join(dirpath, "__pycache__"), ignore_errors=True)
            removed += 1
        # End-if
        for fn in filenames:
            if fn.endswith((".pyc", ".pyo")):
                os.remove(os.path.join(dirpath, fn))
                removed += 1
            # End-if
        # End-for
    # End-for
    print("[+] Removed " + str(removed) + " bytecode items.")

    # Remove build artifacts.
    cfg = _load_config()
    for key in ("output_dir", "cache_dir"):
        path = os.path.join(ROOT_DIR, cfg.get("build", key, fallback=""))
        if os.path.exists(path):
            shutil.rmtree(path, ignore_errors=True)
            print("[+] Removed " + os.path.relpath(path, ROOT_DIR))
        # End-if
    # End-for

    # Legacy dist/ directory.
    legacy = os.path.join(ROOT_DIR, "dist")
    if os.path.exists(legacy):
        shutil.rmtree(legacy, ignore_errors=True)
        print("[+] Removed dist/ (legacy)")
    # End-if
# End-def

##
 # @brief Target: print project name and version.
 #
def target_version():
    name, version = _project_meta()
    print("[+] " + name + " " + version)
# End-def

##
 # @brief Target: sign Windows executable (placeholder for P3).
 #
def target_sign():
    cfg = _load_config()
    enabled = cfg.getboolean("sign", "enabled", fallback=False)
    if not enabled:
        print("[-] Signing is disabled (mk/config/build.config [sign] enabled=false).")
        print("    Nothing to do.")
        return
    # End-if
    print("[-] Signing is not implemented yet (planned for P3).")
    sys.exit(1)
# End-def

##
 # @brief Target: print usage help.
 #
def target_help():
    print(USAGE)
# End-def

##
 # @brief Entry point: dispatch make targets.
 #
def main():
    target = sys.argv[1] if len(sys.argv) > 1 else "all"

    handlers = {
        "all": target_all,
        "clean": target_clean,
        "version": target_version,
        "sign": target_sign,
        "help": target_help,
        "-h": target_help,
        "--help": target_help,
    }

    handler = handlers.get(target)
    if handler is None:
        print("[-] Unknown target: " + target)
        print(USAGE)
        sys.exit(1)
    # End-if

    handler()
# End-def

if __name__ == "__main__":
    main()
