##
 # @file src/subagent/pool.py
 # @date 2026/08/07
 # 
 # @brief Control all subagent.py
 # A global singleton, held by MyAgent, used to maintaining and managing all derived SubAgents. 
 # When you need to create a new SubAgent, this scheduler assigns an ID, mounts specific toolset,
 # and tracks their execution status.
 #

import uuid
from .subagent import SubAgent
from .result import SubAgentResult
from .registry import resolve_toolset

##
 # @brief Subagent Pool.
 #
class SubAgentPool:
    ##
     # @brief Constructor.
     #
     # @param safe_client llm_request client.
     # @param logger log management.
     # @param config environment config.
     # @param all_tools all tools, used to resolve toolset to subagents.
     # @param max_depth subagent's max recursion depth.
     #
    def __init__(self, safe_client, logger, config, all_tools, max_depth=3):
        self.safe_client = safe_client
        self.logger = logger
        self.config = config
        self.all_tools = all_tools
        self.max_depth = max_depth
        self.completed_results = []
    # End-def

    ##
     # @brief Create and run a SubAgent in one call, then record the result.
     #
     # Flow: 
     # 1. assign a sa-<hex> id -> 
     # 2. resolve toolset (failure -> "failed" result) -> 
     # 3. construct SubAgent with routing context -> 
     # 4. SubAgent.run() (exception -> "failed" result collecting sub_results) -> 
     # 5. append to completed_results -> 
     # 6. return.
     #
     # @note Called by SpawnSubagentTool (depth=0, no parent_tools) and
     # RestrictedSpawnTool (depth+1, parent_tools = parent's toolset),
     # both in src/tool/agent/spawn_tool.py.
     #
     # @param role_prompt SubAgent's system prompt, generated by the parent's plan tool.
     # @param toolset_name Toolset name resolved via TOOLSET_REGISTRY.
     # @param task_description SubAgent's task text.
     # @param depth SubAgent's recursion depth (>=1 means sub-sub-agent).
     # @param parent_tools Parent's toolset; restricts the resolved toolset.
     #
     # @return SubAgentResult (status "success" or "failed").
     #
    def create_and_run(
        self,
        role_prompt: str,
        toolset_name: str,
        task_description: str,
        depth: int = 0,
        parent_tools: set = None
    ) -> SubAgentResult:
        subagent_id = f"sa-{uuid.uuid4().hex[:8]}"

        # Tool Error
        try:
            tools = resolve_toolset(toolset_name, self.all_tools, parent_tools)
        except ValueError as e:
            err_msg = f"{e!s}"
            self.logger.log_api_call(f"SUBAGENT:{subagent_id} INIT ERROR", {"error": err_msg})
            result = SubAgentResult(
                subagent_id=subagent_id,
                task_description=task_description,
                status="failed",
                summary="Failed to initialize SubAgent. Invalid toolset.",
                depth_reached=depth,
                error_message=err_msg
            )
            self.completed_results.append(result)
            return result
        # End-except

        subagent = SubAgent(
            safe_client=self.safe_client,
            logger=self.logger,
            config=self.config,
            pool=self,
            role_prompt=role_prompt,
            tools=tools,
            depth=depth,
            max_depth=self.max_depth,
            subagent_id=subagent_id,
            routing_context={
                "task_description": task_description,
                "toolset_name": toolset_name,
                "depth": depth,
            }
        )

        # Runtime Error (Fallback)
        try:
            result = subagent.run(task_description)
        except Exception as e:
            err_msg = f"Unexpected error during execution: {e!s}"
            self.logger.log_api_call(f"SUBAGENT:{subagent_id} EXEC ERROR", {"error": err_msg})

            subagent_instance = locals().get('subagent')
            sub_res = getattr(subagent_instance, 'sub_results', []) if subagent_instance else []

            max_depth_reached = depth
            if sub_res:
                max_depth_reached = max([depth] + [r.depth_reached for r in sub_res])

            result = SubAgentResult(
                subagent_id=subagent_id,
                task_description=task_description,
                status="failed",
                summary="SubAgent execution crashed heavily.",
                depth_reached=max_depth_reached,
                error_message=err_msg,
                sub_results=sub_res
            )
        # End-except

        self.completed_results.append(result)
        return result
    # End-def

    ##
     # @brief Render an execution summary of all completed SubAgents.
     #
     # @note No current caller (reserved for CLI / logging display).
     #
     # @return Multi-line summary string; "(No SubAgents executed)" when empty.
     #
    def get_summary(self) -> str:
        if not self.completed_results:
            return "(No SubAgents executed)"

        lines = ["=== SubAgent Execution Summary ==="]
        for r in self.completed_results:
            status_mark = "+" if r.status == "success" else "!"
            lines.append(
                f"  [{status_mark}] {r.subagent_id}: {r.task_description[:60]}... "
                f"({r.tool_calls_made} calls, depth={r.depth_reached})"
            )
        return "\n".join(lines)
    # End-def
# End-class